# Generated by Django 3.2.3 on 2021-05-24 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_rename_review_title_moviereview_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to='accounts.user'),
            preserve_default=False,
        ),
    ]
