# Generated by Django 3.2.3 on 2021-05-24 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0013_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='like',
            field=models.ManyToManyField(related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
