# Generated by Django 3.2.3 on 2021-05-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20210524_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
